//go:build integration

package app

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

func userAuthorizationIntegrationService(t *testing.T) *Service {
	t.Helper()
	root, dsn := integrationPool(t)
	ctx := context.Background()
	schema := fmt.Sprintf("user_authorization_%d", time.Now().UnixNano())
	name := pgx.Identifier{schema}.Sanitize()
	if _, err := root.Exec(ctx, "create schema "+name); err != nil {
		root.Close()
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if _, err := root.Exec(ctx, "drop schema "+name+" cascade"); err != nil {
			t.Error(err)
		}
		root.Close()
	})
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	cfg.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(pool.Close)
	if _, err := pool.Exec(ctx, `create table users(id bigint generated by default as identity (start with 10) primary key, role text not null, enabled boolean not null default true, email text not null default '', name text not null default '', password_hash text not null default '', must_change_password boolean not null default false); create table user_permissions(user_id bigint references users(id), permission text not null, primary key(user_id,permission)); create table user_sessions(user_id bigint references users(id), token_hash text, expires_at timestamptz default now()+interval '1 hour', reauthenticated_at timestamptz); create table user_wallets(user_id bigint primary key references users(id)); create table api_keys(user_id bigint references users(id), revoked_at timestamptz); insert into users(id,role) values(1,'admin'),(2,'admin'),(3,'user'),(4,'user'); insert into user_permissions values(3,'users.manage');`); err != nil {
		t.Fatal(err)
	}
	return &Service{db: pool}
}

func userAuthorizationRequest(handler http.HandlerFunc, actor accountContext, target, body string) *httptest.ResponseRecorder {
	r := httptest.NewRequest(http.MethodPut, "/admin/users/"+target, strings.NewReader(body))
	r.SetPathValue("id", target)
	r = r.WithContext(context.WithValue(r.Context(), accountContextKey{}, actor))
	w := httptest.NewRecorder()
	handler(w, r)
	return w
}

func TestIntegrationUserAuthorizationRevalidatesQueuedSession(t *testing.T) {
	for _, tc := range []struct {
		name   string
		change string
		want   int
	}{
		{"revoked", `delete from user_sessions where user_id=1`, http.StatusUnauthorized},
		{"expired", `update user_sessions set expires_at=clock_timestamp()-interval '1 second' where user_id=1`, http.StatusUnauthorized},
		{"reauth expired", `update user_sessions set reauthenticated_at=clock_timestamp()-interval '6 minutes' where user_id=1`, http.StatusForbidden},
		{"password reset", `update users set must_change_password=true where id=1`, http.StatusUnauthorized},
	} {
		t.Run(tc.name, func(t *testing.T) {
			s := userAuthorizationIntegrationService(t)
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			if _, err := s.db.Exec(ctx, `insert into user_sessions(user_id,token_hash,reauthenticated_at) values(1,'fake-session-hash',clock_timestamp())`); err != nil {
				t.Fatal(err)
			}
			blocker, err := s.db.Begin(ctx)
			if err != nil {
				t.Fatal(err)
			}
			defer blocker.Rollback(ctx)
			if _, err := blocker.Exec(ctx, `select pg_advisory_xact_lock(458111)`); err != nil {
				t.Fatal(err)
			}
			started := make(chan struct{})
			result := make(chan *httptest.ResponseRecorder, 1)
			verified := time.Now()
			go func() {
				close(started)
				result <- userAuthorizationRequest(s.updateUser, accountContext{userID: "1", role: "admin", sessionHash: "fake-session-hash", reauthenticatedAt: &verified}, "4", `{"name":"queued-update"}`)
			}()
			<-started
			if _, err := blocker.Exec(ctx, tc.change); err != nil {
				t.Fatal(err)
			}
			if err := blocker.Commit(ctx); err != nil {
				t.Fatal(err)
			}
			select {
			case w := <-result:
				if w.Code != tc.want {
					t.Fatalf("status=%d want=%d body=%s", w.Code, tc.want, w.Body.String())
				}
			case <-ctx.Done():
				t.Fatal(ctx.Err())
			}
			var name string
			if err := s.db.QueryRow(ctx, `select name from users where id=4`).Scan(&name); err != nil || name != "" {
				t.Fatalf("revoked request changed target: %q err=%v", name, err)
			}
		})
	}
}

func TestIntegrationUserAuthorizationReauthUsesPostLockClock(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	tx, err := s.db.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	var started time.Time
	if err := tx.QueryRow(ctx, `select now()`).Scan(&started); err != nil {
		t.Fatal(err)
	}
	if _, err := s.db.Exec(ctx, `insert into user_sessions(user_id,token_hash,reauthenticated_at) values(1,'fake-session-hash',$1::timestamptz-interval '5 minutes'+interval '25 milliseconds')`, started); err != nil {
		t.Fatal(err)
	}
	if _, err := tx.Exec(ctx, `select pg_sleep(0.05)`); err != nil {
		t.Fatal(err)
	}
	verified := started
	ctx = context.WithValue(ctx, accountContextKey{}, accountContext{userID: "1", role: "admin", sessionHash: "fake-session-hash", reauthenticatedAt: &verified})
	if _, _, err := lockUserMutation(ctx, tx, "1", "4", userMutation{}, true); err != errUserMutationReauthentication {
		t.Fatalf("stale transaction clock accepted expired verification: %v", err)
	}
}

func TestIntegrationUserAuthorizationProfileProtection(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	manager := accountContext{userID: "3", role: "user", permissions: map[string]bool{"users.manage": true}}
	for _, target := range []string{"1", "2", "3"} {
		for _, body := range []string{`{"email":"takeover@example.test"}`, `{"password":"fake-test-password"}`, `{"name":"takeover"}`, `{"enabled":false}`} {
			w := userAuthorizationRequest(s.updateUser, manager, target, body)
			if w.Code != http.StatusForbidden {
				t.Fatalf("target=%s body=%s status=%d response=%s", target, body, w.Code, w.Body.String())
			}
		}
	}
	w := userAuthorizationRequest(s.updateUser, manager, "4", `{"email":"ordinary@example.test","password":"fake-test-password"}`)
	if w.Code != http.StatusOK {
		t.Fatalf("ordinary profile should be editable: status=%d response=%s", w.Code, w.Body.String())
	}
	if _, err := s.db.Exec(context.Background(), `insert into user_permissions values(4,'system.manage')`); err != nil {
		t.Fatal(err)
	}
	w = userAuthorizationRequest(s.updateUser, manager, "4", `{"email":"takeover@example.test"}`)
	if w.Code != http.StatusForbidden {
		t.Fatalf("permission-bearing user profile not protected: %d %s", w.Code, w.Body.String())
	}
}

func TestIntegrationUserAuthorizationSelfAliasesAndSessionRevocation(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	admin := accountContext{userID: "1", role: "admin"}
	for _, tc := range []struct {
		handler http.HandlerFunc
		body    string
	}{
		{s.setUserRole, `{"role":"user"}`},
		{s.setUserPermissions, `{"permissions":[]}`},
		{s.updateUser, `{"role":"admin"}`},
	} {
		w := userAuthorizationRequest(tc.handler, admin, "01", tc.body)
		if w.Code != http.StatusForbidden {
			t.Fatalf("self ID alias bypassed authorization: %d %s", w.Code, w.Body.String())
		}
	}
	for _, tc := range []struct {
		handler http.HandlerFunc
		body    string
	}{
		{s.setUserRole, `{"role":"operator"}`},
		{s.setUserPermissions, `{"permissions":["logs.read"]}`},
		{s.updateUser, `{"permissions":[]}`},
		{s.updateUser, `{"email":"changed@example.test"}`},
	} {
		if _, err := s.db.Exec(context.Background(), `insert into user_sessions values(4)`); err != nil {
			t.Fatal(err)
		}
		w := userAuthorizationRequest(tc.handler, admin, "4", tc.body)
		if w.Code != http.StatusOK {
			t.Fatalf("admin update failed: %d %s", w.Code, w.Body.String())
		}
		var count int
		if err := s.db.QueryRow(context.Background(), `select count(*) from user_sessions where user_id=4`).Scan(&count); err != nil || count != 0 {
			t.Fatalf("sessions survive security mutation: count=%d err=%v", count, err)
		}
	}
}

func TestIntegrationUserAuthorizationCreateAndStaleActor(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	admin := accountContext{userID: "1", role: "admin"}
	manager := accountContext{userID: "3", role: "user", permissions: map[string]bool{"users.manage": true}}
	for _, tc := range []struct {
		actor accountContext
		body  string
		want  int
	}{
		{manager, `{"email":"ordinary@example.test","name":"ordinary","password":"fake-test-password","role":"user"}`, http.StatusCreated},
		{manager, `{"email":"fake@example.test","name":"fake","password":"fake-test-password","role":"admin"}`, http.StatusForbidden},
		{manager, `{"email":"fake@example.test","name":"fake","password":"fake-test-password","permissions":["users.authorize"]}`, http.StatusForbidden},
		{admin, `{"email":"admin@example.test","name":"admin","password":"fake-test-password","role":"admin"}`, http.StatusCreated},
	} {
		w := userAuthorizationRequest(s.createUser, tc.actor, "", tc.body)
		if w.Code != tc.want {
			t.Fatalf("create status=%d want=%d response=%s", w.Code, tc.want, w.Body.String())
		}
	}
	if _, err := s.db.Exec(context.Background(), `delete from user_permissions where user_id=3`); err != nil {
		t.Fatal(err)
	}
	w := userAuthorizationRequest(s.updateUser, manager, "4", `{"name":"stale-manager"}`)
	if w.Code != http.StatusForbidden {
		t.Fatalf("stale actor passed mutation: %d %s", w.Code, w.Body.String())
	}
}

func TestIntegrationUserAuthorizationConcurrentDemotions(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	ctx := context.Background()
	for iteration := 0; iteration < 8; iteration++ {
		if _, err := s.db.Exec(ctx, `update users set role='admin', enabled=true where id in (1,2)`); err != nil {
			t.Fatal(err)
		}
		handler, body := s.setUserRole, `{"role":"user"}`
		if iteration%2 == 1 {
			handler, body = s.updateUser, `{"enabled":false}`
		}
		start := make(chan struct{})
		results := make(chan *httptest.ResponseRecorder, 2)
		for _, pair := range [][2]string{{"1", "2"}, {"2", "1"}} {
			go func() {
				<-start
				results <- userAuthorizationRequest(handler, accountContext{userID: pair[0], role: "admin"}, pair[1], body)
			}()
		}
		close(start)
		succeeded := 0
		for range 2 {
			w := <-results
			if w.Code == http.StatusOK {
				succeeded++
			} else if w.Code != http.StatusForbidden && w.Code != http.StatusConflict {
				t.Fatalf("unexpected concurrent response %d %s", w.Code, w.Body.String())
			}
		}
		var admins int
		if err := s.db.QueryRow(ctx, `select count(*) from users where role='admin' and enabled`).Scan(&admins); err != nil {
			t.Fatal(err)
		}
		if succeeded != 1 || admins != 1 {
			t.Fatalf("concurrent demotions violated invariant: successes=%d admins=%d", succeeded, admins)
		}
	}
}

func TestIntegrationUserAuthorizationConcurrentProfileAndPromotion(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	ctx := context.Background()
	tx, err := s.db.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	if _, err := tx.Exec(ctx, `select pg_advisory_xact_lock(458111)`); err != nil {
		t.Fatal(err)
	}
	result := make(chan *httptest.ResponseRecorder, 1)
	go func() {
		result <- userAuthorizationRequest(s.updateUser, accountContext{userID: "3", role: "user", permissions: map[string]bool{"users.manage": true}}, "4", `{"email":"takeover@example.test"}`)
	}()
	if _, err := tx.Exec(ctx, `insert into user_permissions values(4,'system.manage')`); err != nil {
		t.Fatal(err)
	}
	if err := tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	w := <-result
	if w.Code != http.StatusForbidden {
		t.Fatalf("profile mutation used stale target authorization: %d %s", w.Code, w.Body.String())
	}
	var email string
	if err := s.db.QueryRow(ctx, `select email from users where id=4`).Scan(&email); err != nil || email != "" {
		t.Fatalf("privileged email modified: %q err=%v", email, err)
	}
}

func TestIntegrationUserUpdateAlreadyEnabledDoesNotReleaseRewardBan(t *testing.T) {
	s := userAuthorizationIntegrationService(t)
	w := userAuthorizationRequest(s.updateUser, accountContext{userID: "1", role: "admin"}, "4", `{"name":"updated-name","enabled":true}`)
	if w.Code != http.StatusOK {
		t.Fatalf("already-enabled profile update failed: %d %s", w.Code, w.Body.String())
	}
	var name string
	if err := s.db.QueryRow(context.Background(), `select name from users where id=4`).Scan(&name); err != nil || name != "updated-name" {
		t.Fatalf("name = %q err=%v", name, err)
	}
}
