-- Convert channels.id and every foreign key onto it from uuid to numeric ids.
-- Existing rows keep a stable id assigned in (created_at, id) order, and every
-- referencing table is re-keyed to match so no history is lost.

-- Drop the foreign keys that reference channels(id).
alter table request_logs drop constraint if exists request_logs_channel_id_fkey;
alter table channel_groups drop constraint if exists channel_groups_channel_id_fkey;
alter table channel_api_keys drop constraint if exists channel_api_keys_channel_id_fkey;
alter table model_routes drop constraint if exists model_routes_channel_id_fkey;
alter table channel_quota_limits drop constraint if exists channel_quota_limits_channel_id_fkey;

-- Drop the unique/primary constraints that include channel_id on child tables.
alter table channel_groups drop constraint if exists channel_groups_pkey;
alter table model_routes drop constraint if exists model_routes_public_model_channel_id_key;
alter table channel_quota_limits drop constraint if exists channel_quota_limits_channel_id_window_key;

-- Re-key channels in stable order.
alter table channels add column new_id bigint;
update channels c
set new_id = seq.rn
from (select id, row_number() over (order by created_at, id) as rn from channels) seq
where c.id = seq.id;
alter table channels alter column new_id set not null;

alter table channels drop constraint channels_pkey;
alter table channels drop column id;
alter table channels rename column new_id to id;
alter table channels add primary key (id);
alter table channels alter column id add generated by default as identity;

-- Re-key channel_api_keys.
alter table channel_api_keys add column new_channel_id bigint;
update channel_api_keys k set new_channel_id = c.id from channels c where c.id = k.channel_id;
alter table channel_api_keys drop column channel_id;
alter table channel_api_keys rename column new_channel_id to channel_id;
alter table channel_api_keys alter column channel_id set not null;
alter table channel_api_keys add constraint channel_api_keys_channel_id_fkey foreign key (channel_id) references channels(id) on delete cascade;

-- Re-key channel_groups.
alter table channel_groups add column new_channel_id bigint;
update channel_groups g set new_channel_id = c.id from channels c where c.id = g.channel_id;
alter table channel_groups drop column channel_id;
alter table channel_groups rename column new_channel_id to channel_id;
alter table channel_groups alter column channel_id set not null;
alter table channel_groups add primary key (channel_id, group_id);
alter table channel_groups add constraint channel_groups_channel_id_fkey foreign key (channel_id) references channels(id) on delete cascade;

-- Re-key model_routes.
alter table model_routes add column new_channel_id bigint;
update model_routes r set new_channel_id = c.id from channels c where c.id = r.channel_id;
alter table model_routes drop column channel_id;
alter table model_routes rename column new_channel_id to channel_id;
alter table model_routes alter column channel_id set not null;
alter table model_routes add constraint model_routes_public_model_channel_id_key unique (public_model, channel_id);
alter table model_routes add constraint model_routes_channel_id_fkey foreign key (channel_id) references channels(id) on delete cascade;

-- Re-key channel_quota_limits.
alter table channel_quota_limits add column new_channel_id bigint;
update channel_quota_limits q set new_channel_id = c.id from channels c where c.id = q.channel_id;
alter table channel_quota_limits drop column channel_id;
alter table channel_quota_limits rename column new_channel_id to channel_id;
alter table channel_quota_limits alter column channel_id set not null;
alter table channel_quota_limits add constraint channel_quota_limits_channel_id_window_key unique (channel_id, "window");
alter table channel_quota_limits add constraint channel_quota_limits_channel_id_fkey foreign key (channel_id) references channels(id) on delete cascade;

-- request_logs keeps a nullable channel_id referencing channels(id) on delete set null.
alter table request_logs add column new_channel_id bigint;
update request_logs rl set new_channel_id = c.id from channels c where c.id = rl.channel_id;
alter table request_logs drop column channel_id;
alter table request_logs rename column new_channel_id to channel_id;
alter table request_logs add constraint request_logs_channel_id_fkey foreign key (channel_id) references channels(id) on delete set null;
