-- Rich model metadata generated from the reviewed official specification set.
-- Descriptions are intentionally untouched; unknown fields retain prior values during merge.
with incoming(model,name,owned_by,input_modalities,output_modalities,context_window,max_output_tokens,reasoning_efforts,api_capabilities) as (
  values
    ('MiniMax-M2','MiniMax-M2','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M2.1','MiniMax-M2.1','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M2.1-highspeed','MiniMax-M2.1-highspeed','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M2.5','MiniMax-M2.5','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M2.5-highspeed','MiniMax-M2.5-highspeed','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M2.7','MiniMax-M2.7','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M2.7-highspeed','MiniMax-M2.7-highspeed','minimax',ARRAY['text']::text[],ARRAY['text']::text[],204800,204800,null::jsonb,null::jsonb),
    ('MiniMax-M3','MiniMax-M3','minimax',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,524288,null::jsonb,null::jsonb),
    ('codex-auto-review','Codex Auto Review','',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('deepseek-flash','DeepSeek V4.1 Flash','deepseek',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,393216,'{"supported_levels":["low","high","max"],"default_level":"high"}'::jsonb,null::jsonb),
    ('deepseek-v4-flash','DeepSeek V4 Flash','deepseek',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,393216,'{"supported_levels":["low","high","max"],"default_level":"high"}'::jsonb,null::jsonb),
    ('deepseek-v4-flash-vision','DeepSeek V4 Flash Vision','deepseek',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('deepseek-v4-pro','DeepSeek V4 Pro','deepseek',ARRAY['text']::text[],ARRAY['text']::text[],1000000,393216,'{"supported_levels":["low","high","max"],"default_level":"high"}'::jsonb,null::jsonb),
    ('deepseek-v4-pro-0813','DeepSeek V4 Pro (0813)','deepseek',ARRAY['text']::text[],ARRAY['text']::text[],1000000,393216,'{"supported_levels":["low","high","max"],"default_level":"high"}'::jsonb,null::jsonb),
    ('deepseek-v4.1-flash','DeepSeek V4.1 Flash','deepseek',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,393216,'{"supported_levels":["low","high","max"],"default_level":"high"}'::jsonb,null::jsonb),
    ('doubao-seed-2.0-lite','Doubao Seed 2.0 Lite','bytedance',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('doubao-seed-2.1-turbo','Doubao Seed 2.1 Turbo','bytedance',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('doubao-seed-evolving','Doubao Seed Evolving','bytedance',ARRAY['text','image','video','file']::text[],ARRAY['text']::text[],1024000,256000,'{"supported_levels":["minimal","low","medium","high","xhigh","max"],"default_level":"high"}'::jsonb,null::jsonb),
    ('glm-4-32b','GLM-4-32B-0414','zai',ARRAY['text']::text[],ARRAY['text']::text[],32768,null,null::jsonb,null::jsonb),
    ('glm-4.5','GLM-4.5','zai',ARRAY['text']::text[],ARRAY['text']::text[],128000,98304,null::jsonb,null::jsonb),
    ('glm-4.5-air','GLM-4.5-Air','zai',ARRAY['text']::text[],ARRAY['text']::text[],128000,98304,null::jsonb,null::jsonb),
    ('glm-4.5v','GLM-4.5V','zai',ARRAY['text','image','video','file']::text[],ARRAY['text']::text[],64000,16384,null::jsonb,null::jsonb),
    ('glm-4.6','GLM-4.6','zai',ARRAY['text']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('glm-4.6v','GLM-4.6V','zai',ARRAY['text','image','video','file']::text[],ARRAY['text']::text[],128000,32768,null::jsonb,null::jsonb),
    ('glm-4.7','GLM-4.7','zai',ARRAY['text']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('glm-4.7-flash','GLM-4.7-Flash','zai',ARRAY['text']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('glm-5','GLM-5','zai',ARRAY['text']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('glm-5-turbo','GLM-5-Turbo','zai',ARRAY['text']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('glm-5.1','GLM-5.1','zai',ARRAY['text']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('glm-5.2','GLM-5.2','zai',ARRAY['text']::text[],ARRAY['text']::text[],1000000,131072,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"max"}'::jsonb,null::jsonb),
    ('glm-5.2-fast-preview','GLM-5.2 Fast Preview','zai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('glm-5.3','GLM-5.3','zai',ARRAY['text']::text[],ARRAY['text']::text[],1000000,131072,'{"supported_levels":["low","high","max"],"default_level":"max"}'::jsonb,null::jsonb),
    ('glm-5.3-flash','GLM-5.3-Flash','zai',ARRAY['text','image','video','file']::text[],ARRAY['text']::text[],1000000,131072,'{"supported_levels":["low","high","max"],"default_level":"max"}'::jsonb,null::jsonb),
    ('glm-5.3-flashx','GLM-5.3-FlashX','zai',ARRAY['text','image','video','file']::text[],ARRAY['text']::text[],1000000,131072,'{"supported_levels":["low","high","max"],"default_level":"max"}'::jsonb,null::jsonb),
    ('glm-5v-turbo','GLM-5V-TURBO','zai',ARRAY['text','image','video','file']::text[],ARRAY['text']::text[],200000,131072,null::jsonb,null::jsonb),
    ('gpt-4o-audio-preview','GPT-4o Audio Preview','openai',ARRAY['text','audio']::text[],ARRAY['text','audio']::text[],128000,16384,null::jsonb,null::jsonb),
    ('gpt-4o-realtime-preview','GPT-4o Realtime Preview','openai',ARRAY['text','audio']::text[],ARRAY['text','audio']::text[],32000,4096,null::jsonb,null::jsonb),
    ('gpt-5.2','GPT-5.2','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],400000,128000,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"none"}'::jsonb,null::jsonb),
    ('gpt-5.2-2025-12-11','GPT-5.2 (2025-12-11)','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],400000,128000,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"none"}'::jsonb,null::jsonb),
    ('gpt-5.2-chat-latest','GPT-5.2 Chat','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],128000,16384,null::jsonb,null::jsonb),
    ('gpt-5.2-pro','GPT-5.2 Pro','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],400000,128000,'{"supported_levels":["medium","high","xhigh"]}'::jsonb,null::jsonb),
    ('gpt-5.2-pro-2025-12-11','GPT-5.2 Pro (2025-12-11)','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],400000,128000,'{"supported_levels":["medium","high","xhigh"]}'::jsonb,null::jsonb),
    ('gpt-5.3-codex-spark','GPT-5.3-Codex-Spark','openai',ARRAY['text']::text[],ARRAY['text']::text[],128000,null,null::jsonb,null::jsonb),
    ('gpt-5.4','GPT-5.4','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"none"}'::jsonb,null::jsonb),
    ('gpt-5.4-2026-03-05','GPT-5.4 (2026-03-05)','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"none"}'::jsonb,null::jsonb),
    ('gpt-5.4-mini','GPT-5.4 Mini','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],400000,128000,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"none"}'::jsonb,null::jsonb),
    ('gpt-5.4-mini-openai-compact','GPT-5.4 Mini (OpenAI Compact)','openai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-5.4-openai-compact','GPT-5.4 (OpenAI Compact)','openai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-5.5','GPT-5.5','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-5.5-openai-compact','GPT-5.5 (OpenAI Compact)','openai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-5.6','GPT-5.6','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-5.6-luna','GPT-5.6 Luna','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-5.6-sol','GPT-5.6 Sol','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-5.6-terra','GPT-5.6 Terra','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-6','GPT-6','openai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-6-astra','GPT-6 Astra','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"]}'::jsonb,null::jsonb),
    ('gpt-6-luna','GPT-6 Luna','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-6-sol','GPT-6 Sol','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-6.1-sol','GPT-6.1 Sol','openai',ARRAY['text','image']::text[],ARRAY['text']::text[],1050000,128000,'{"supported_levels":["low","medium","high","xhigh","max"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('gpt-image-1','GPT Image 1','openai',ARRAY['text','image']::text[],ARRAY['image']::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-image-1.5','GPT Image 1.5','openai',ARRAY['text','image']::text[],ARRAY['image','text']::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-image-2','GPT Image 2','openai',ARRAY['text','image']::text[],ARRAY['image']::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-image-2.5','GPT Image 2.5','openai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-image-2.5-flare','GPT Image 2.5 Flare','openai',ARRAY['text','image']::text[],ARRAY['image']::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-image-2.5-sunburst','GPT Image 2.5 Sunburst','openai',ARRAY['text','image']::text[],ARRAY['image']::text[],null,null,null::jsonb,null::jsonb),
    ('gpt-reserve','GPT Reserve','openai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('grok','Grok','xai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('grok-4','Grok 4','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],256000,null,null::jsonb,null::jsonb),
    ('grok-4-0709','Grok 4 (0709)','xai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('grok-4.20-0309-non-reasoning','Grok 4.20 Non-Reasoning (0309)','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('grok-4.20-0309-reasoning','Grok 4.20 Reasoning (0309)','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('grok-4.20-multi-agent-0309','Grok 4.20 Multi-Agent Beta (0309)','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,null,'{"supported_levels":["low","medium","high","xhigh"]}'::jsonb,null::jsonb),
    ('grok-4.20-non-reasoning','Grok 4.20 Non-Reasoning','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('grok-4.20-reasoning','Grok 4.20 Reasoning','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('grok-4.3','Grok 4.3','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],1000000,null,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"low"}'::jsonb,null::jsonb),
    ('grok-4.5','Grok 4.5','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],500000,null,'{"supported_levels":["low","medium","high"],"default_level":"high"}'::jsonb,null::jsonb),
    ('grok-4.5-latest','Grok 4.5 Latest','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],500000,null,'{"supported_levels":["low","medium","high"],"default_level":"high"}'::jsonb,null::jsonb),
    ('grok-4.6','Grok 4.6','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],500000,null,'{"supported_levels":["low","medium","high","xhigh"],"default_level":"high"}'::jsonb,null::jsonb),
    ('grok-build','Grok Build','xai',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('grok-build-0.1','Grok Build 0.1','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],256000,null,null::jsonb,null::jsonb),
    ('grok-build-latest','Grok Build Latest (Grok 4.5)','xai',ARRAY['text','image']::text[],ARRAY['text']::text[],500000,null,'{"supported_levels":["low","medium","high"],"default_level":"high"}'::jsonb,null::jsonb),
    ('hy3','Hy3','tencent',ARRAY['text']::text[],ARRAY['text']::text[],256000,null,null::jsonb,null::jsonb),
    ('hy3-preview','Hy3 Preview','tencent',ARRAY['text']::text[],ARRAY['text']::text[],256000,null,null::jsonb,null::jsonb),
    ('hy4-preview','Hy4 Preview','tencent',ARRAY['text']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('kimi-k2.5','Kimi K2.5','moonshot',ARRAY['text','image','video']::text[],ARRAY['text']::text[],262144,null,null::jsonb,null::jsonb),
    ('kimi-k2.6','Kimi K2.6','moonshot',ARRAY['text','image','video']::text[],ARRAY['text']::text[],262144,null,null::jsonb,null::jsonb),
    ('kimi-k2.7-code','Kimi K2.7 Code','moonshot',ARRAY['text','image','video']::text[],ARRAY['text']::text[],262144,null,null::jsonb,null::jsonb),
    ('kimi-k2.8-preview','Kimi K2.8 Preview','moonshot',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('kimi-k3','Kimi K3','moonshot',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1048576,1048576,'{"supported_levels":["low","high","max"],"default_level":"max"}'::jsonb,null::jsonb),
    ('kimi-k3-256k','Kimi K3 256K','moonshot',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('laguna-s-2.1','Laguna S 2.1','poolside',ARRAY['text']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('longcat-2.0','LongCat 2.0','meituan',ARRAY['text']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('mimo-v2-omni','MiMo V2 Omni','xiaomi',ARRAY['text','image','audio','video']::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('mimo-v2-pro','MiMo V2 Pro','xiaomi',ARRAY['text']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('mimo-v2.5','MiMo V2.5','xiaomi',ARRAY['text','image','audio','video']::text[],ARRAY['text']::text[],1000000,128000,null::jsonb,null::jsonb),
    ('mimo-v2.5-pro','MiMo V2.5 Pro','xiaomi',ARRAY['text']::text[],ARRAY['text']::text[],1000000,128000,null::jsonb,null::jsonb),
    ('mimo-v2.6-flash','MiMo V2.6 Flash','xiaomi',ARRAY['text','image','audio','video']::text[],ARRAY['text']::text[],1000000,128000,null::jsonb,null::jsonb),
    ('mimo-v2.6-pro','MiMo V2.6 Pro','xiaomi',ARRAY['text','image','audio','video']::text[],ARRAY['text']::text[],1000000,128000,null::jsonb,null::jsonb),
    ('mistral-large-3','Mistral Large 3','mistral',ARRAY['text','image']::text[],ARRAY['text']::text[],256000,null,null::jsonb,null::jsonb),
    ('muse-spark-1.2-contributor','Muse Spark 1.2 Contributor','meta',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('nemotron-3-super','NVIDIA Nemotron 3 Super','nvidia',ARRAY['text']::text[],ARRAY['text']::text[],1000000,null,null::jsonb,null::jsonb),
    ('nemotron-3-ultra','NVIDIA Nemotron 3 Ultra','nvidia',ARRAY['text']::text[],ARRAY['text']::text[],null,null,null::jsonb,null::jsonb),
    ('qwen-vl-ocr','Qwen-vl-ocr','qwen',ARRAY['text','image']::text[],ARRAY['text']::text[],38192,8192,null::jsonb,null::jsonb),
    ('qwen3.5-omni-flash','Qwen3.5-omni-flash','qwen',ARRAY['text','image','audio','video']::text[],ARRAY['text','audio']::text[],262144,65536,null::jsonb,null::jsonb),
    ('qwen3.5-omni-plus','Qwen3.5-omni-plus','qwen',ARRAY['text','image','audio','video']::text[],ARRAY['text','audio']::text[],262144,65536,null::jsonb,null::jsonb),
    ('qwen3.5-plus','Qwen3.5-plus','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,65536,null::jsonb,null::jsonb),
    ('qwen3.6-flash','Qwen3.6-flash','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,65536,null::jsonb,null::jsonb),
    ('qwen3.6-max-preview','Qwen3.6-max-preview','qwen',ARRAY['text']::text[],ARRAY['text']::text[],262144,65536,null::jsonb,null::jsonb),
    ('qwen3.6-plus','Qwen3.6-plus','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,65536,null::jsonb,null::jsonb),
    ('qwen3.7-flash','Qwen3.7-flash','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,131072,null::jsonb,null::jsonb),
    ('qwen3.7-max','Qwen3.7-max','qwen',ARRAY['text']::text[],ARRAY['text']::text[],1000000,131072,null::jsonb,null::jsonb),
    ('qwen3.7-plus','Qwen3.7-plus','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,131072,null::jsonb,null::jsonb),
    ('qwen3.8-27b','Qwen3.8-27B','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],262144,null,'{"supported_levels":["low","medium","xhigh"],"default_level":"xhigh"}'::jsonb,null::jsonb),
    ('qwen3.8-flash','Qwen3.8-flash','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,131072,null::jsonb,null::jsonb),
    ('qwen3.8-max','Qwen3.8-max','qwen',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,131072,null::jsonb,null::jsonb),
    ('seed-2.1-pro','Doubao Seed 2.1 Pro','bytedance',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('seed-2.1-turbo','Doubao Seed 2.1 Turbo','bytedance',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('step-3.5-flash','Step 3.5 Flash','stepfun',ARRAY['text']::text[],ARRAY['text']::text[],256000,null,null::jsonb,null::jsonb),
    ('step-3.5-flash-2603','Step 3.5 Flash (2603)','stepfun',ARRAY['text']::text[],ARRAY['text']::text[],256000,null,'{"supported_levels":["low","high"]}'::jsonb,null::jsonb),
    ('step-3.7-flash','Step 3.7 Flash','stepfun',ARRAY['text','image','video']::text[],ARRAY['text']::text[],256000,null,'{"supported_levels":["low","medium","high"],"default_level":"medium"}'::jsonb,null::jsonb),
    ('step-5-preview','Step 5 Preview','stepfun',ARRAY['text','image','video']::text[],ARRAY['text']::text[],1000000,64000,'{"supported_levels":["low","medium","high"]}'::jsonb,null::jsonb),
    ('step-image-edit-2','Step Image Edit 2','stepfun',ARRAY['text','image']::text[],ARRAY['image']::text[],null,null,null::jsonb,null::jsonb),
    ('step-router-v1','Step Router V1','stepfun',ARRAY[]::text[],ARRAY[]::text[],null,null,null::jsonb,null::jsonb),
    ('stepaudio-2.5-asr','StepAudio 2.5 ASR','stepfun',ARRAY['audio']::text[],ARRAY['text']::text[],null,null,null::jsonb,null::jsonb),
    ('stepaudio-2.5-chat','StepAudio 2.5 Chat','stepfun',ARRAY['text','audio']::text[],ARRAY['text']::text[],null,null,null::jsonb,null::jsonb),
    ('stepaudio-2.5-realtime','StepAudio 2.5 Realtime','stepfun',ARRAY['text','audio']::text[],ARRAY['text','audio']::text[],null,null,null::jsonb,null::jsonb),
    ('stepaudio-2.5-tts','StepAudio 2.5 TTS','stepfun',ARRAY['text','audio']::text[],ARRAY['audio']::text[],null,null,null::jsonb,null::jsonb)
)
insert into model_catalog_metadata(model,name,owned_by,input_modalities,output_modalities,context_window,max_output_tokens,reasoning_efforts,api_capabilities)
select model,name,owned_by,input_modalities,output_modalities,context_window,max_output_tokens,reasoning_efforts,api_capabilities from incoming
on conflict (model) do update set
  name=excluded.name,
  owned_by=excluded.owned_by,
  input_modalities=excluded.input_modalities,
  output_modalities=excluded.output_modalities,
  context_window=excluded.context_window,
  max_output_tokens=excluded.max_output_tokens,
  reasoning_efforts=excluded.reasoning_efforts,
  api_capabilities=excluded.api_capabilities,
  updated_at=now();
